hero/accounts/accounts/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

hero/accounts/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', auth_views.LoginView.as_view(), name='login', kwargs={
        'form_class' : LoginForm
    }),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^logout/$', auth_views.logout, name='logout', kwargs={

        'next_page' : settings.LOGIN_URL,

    }),
]

hero/blog/urls.py
from django.conf.urls import url
# . 현재 디렉토리에서 import
from . import views
from . import views_cbv

# regex, function
# ^ 문자열의 시작 $ 문자열의 끝
# r(regex의 r이 아니라 escape 문자임) '^(문자 시작은 이거로 하고)$(끝나는건 이렇게 끝날거임)'(이 내용임)
# //d = r'/d'임
#
urlpatterns = [


    # url(r'^sum/(?P<x>\d+)/$', views.mysum),
    # sum / 으로 시작해서 (?P 만약 \d에 맞으면 <x> x라는 인자로 return 할게.)
    # url(r'^sum/(?P<x>\d+)/(?P<y>\d+)/$', views.mysum),
    # url(r'^sum/(?P<x>\d+)/(?P<y>\d+)/(?P<z>\d+)/$', views.mysum),
    #     sum/뭔가의 숫자/뭔가의 숫자/뭔가의 숫자/ 에 매칭

    # 10/20/30/40... 의 패턴?
    url(r'^sum/(?P<numbers>[0-9/]+)/$', views.mysum),

    # /hello/한글이름/나이/
    url(r'^hello/(?P<name>[ㄱ-힣]+)/(?P<age>\d+)/$', views.myurl),

    url(r'^$', views.post_list, name='post_list'),
    url(r'^new/$', views_cbv.post_new, name='post_new'),
    url(r'^(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<pk>\d+)/edit/$', views_cbv.post_edit, name='post_edit'),
    url(r'^(?P<pk>\d+)/delete/$', views.post_delete, name='post_delete'),


]

hero/hero/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings

# 내 프로젝트 안 어쩌구 /xxx/mypage.hero 에서 xxx 쪽을 연결 <- 이거용어가 기억이안남
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^weblog/', include('blog.urls', namespace="blog")),

    url(r'^shop/', include('shop.urls', namespace="shop")),
]


# 디버그 툴바

if settings.DEBUG:
    import debug_toolbar

# 디버그 설정되어 있으면 디버그 모드 설정
urlpatterns += [
    url(r'^__debug__/', include(debug_toolbar.urls)),
]

hero/accounts/models.py
from django.db import models

# Create your models here.

hero/blog/models.py
from django.db import models
import os
import uuid;
from django.urls import reverse
from django.core.exceptions import ValidationError

# Create your models here.


# db생성
# 앱 이름_클래스명 으로 db 생성됨
class Post(models.Model) :
    # default 지정
    # author = models.CharField(max_length=15, default="어쩌구")


    def min_length_name(value):
        if len(value) < 2:
            raise ValidationError("두글자 이상 입력하세요")

    author = models.CharField(max_length=15, validators=[min_length_name])
    title = models.CharField(max_length=100, help_text="이름을 넣어주세요", validators=[min_length_name])
    content = models.TextField(help_text="markdown 문법 지원")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta :
        # 기본 정렬 설정
        ordering = ['-id']

    def __str__(self):
        # 제목을 리턴
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.id])



def random_upload_to(instance, orig_filename) :

    ext = os.path.splitext(orig_filename)[-1].lower()
    filename = uuid.uuid4().hex + ext
    filepath = os.path.join(filename[:3], filename[3:6], filename[6:9], filename[9:])

    return filepath

hero/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class SignupForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ('email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].help_text = '내가 원하는 도움말'
        self.fields['email'].help_text = '내가 원하는 Email 도움말'


def check_answer(value):
    if value != 6:
        raise forms.ValidationError('땡~!')

class LoginForm(AuthenticationForm):
    answer = forms.IntegerField(help_text='3+3=?', validators=[check_answer])

hero/blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm) :
    class Meta :
        model = Post
        fields = "__all__"

hero/accounts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect, render
from .forms import SignupForm

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect(settings.LOGIN_URL)
    else:
        form = SignupForm()
    return render(request, 'accounts/signup_form.html', {
        'form': form,
    })


@login_required
def profile(request):
    return render(request, 'accounts/profile.html')

hero/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Post
from django.db.models import Q
from django.shortcuts import redirect, render
from .forms import PostForm

# Create your views here.

# view 화면 연결
def post_list(request) :

    qs = Post.objects.all()
    
    # 쿼리에 해당하는 값 없을 시엔 ''공백 리턴

    query = request.GET.get('query', '')
    type = request.GET.get('type', '')

    #값이 있으면
    
    if query :
        #title__icontains -> 제목에 검색어가 있는 것만 필터링
        #컬럼명__icontains


        if type == 'title' :
            qs = qs.filter(title__icontains=query)
        elif type == 'subject' :
            qs = qs.filter(content__icontains=query)
        else :
            qs = qs.filter(Q(title__icontains=query) | Q(content__icontains=query))

# html 파일 앞 디렉토리를 줘서 충돌을 막음

    return render(request, "blog/post_list.html", {
        
        #post_list 값으로 qs 보내줌
        'post_list' : qs,
        'query' : query
    })


def mysum(request, numbers) :

    result = 0;
    for number in numbers.split("/") :

        if number : # 빈 문자열이 아니라 숫자가 있을 경우엔
            result += int(number)

        # result += int(number or 0) -> number가 거짓일시 뒤 값이 대신 사용


    # 또는 제너레이터 표현식으로 아래와 같이 표현 할 수도 있다

    # sum(int(number or 0) for number in numbers.split("/"))

    return HttpResponse(result)


def myurl(request, name, age) :

    return HttpResponse("안녕하세요, "+name+". "+age+"살이네요.")


def post_detail(request, pk) :

    post = Post.objects.get(pk=pk)

    return render(request, 'blog/post_detail.html', {

        'post' : post,
    })


def post_new(request):
     if request.method == 'POST':
        # request.GET
        # request.POST  # POST인자, 파일 제외
         # request.FILES  # POST인자, 파일만
         form = PostForm(request.POST)
         if form.is_valid():
             # form.cleaned_data  # {'title': ??, 'author': ??}
             post = form.save()
             return redirect(post) # post.get_absolute_url()로 이동
         #else:
         #    form.errors
     else:
         # if request.method == 'GET':
         form = PostForm()
     return render(request, 'blog/post_form.html', {
         'form': form,
     })

def post_edit(request, pk):
    post = Post.objects.get(pk=pk)

    if request.method == 'POST':
            # request.GET
        # request.POST  # POST인자, 파일 제외
        # request.FILES  # POST인자, 파일만
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            # form.cleaned_data  # {'title': ??, 'author': ??}
            post = form.save()
            return redirect('blog:post_detail', post.id)
        #else:
        #    form.errors
    else:
        # if request.method == 'GET':
        form = PostForm(instance=post)

    return render(request, 'blog/post_form.html', {
        'form': form,
    })


def post_delete(request, pk) :

    post = Post.objects.get(pk=pk)


    if request.method == "POST" :
        post.delete()
        return redirect("blog:post_list")

    return render(request, "blog/post_confirm_delete.html", {
        "post" :post,

    })

hero/accounts/templates/accounts/layout.html
{% extends "layout.html" %}

hero/accounts/templates/accounts/profile.html
{% extends "accounts/layout.html" %}

{% block content %}
 <h1>{{ user }}</h1>
 {{ user.date_joined
 {{ user.email }}
{% endblock %}

hero/accounts/templates/accounts/signup_form.html
{% extends "accounts/layout.html" %}
{% load bootstrap3 %}

 {% block content %}
   <form action="" method="post">
         {% csrf_token %}
         {% bootstrap_form form %}
         <input type="submit" class="btn btn-primary btn-block" />
    </form>
 {% endblock %}

hero/accounts/templates/login.html
<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form }}
    </table>


</form>

hero/blog/templates/blog/layout.html
{% extends "layout.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Blog</title>
    <script src="//code.jquery.com/jquery-2.2.4.min.js"></script>

    {% block extra_head %}{% endblock %}
</head>
<body>
<div>
    <h1>BLOG</h1>
    <hr>

    {% block content %}
    {% endblock %}

    <hr>

    &copy; 2017 HERO. All rights reserved.

</div>
</body>
</html>

hero/blog/templates/blog/post_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>삭제</title>
</head>
<body>

<form action="" method="POST">

    {% csrf_token %}

    정말 삭제하시겠습니까?
    <input type="submit" value="넹">
</form>

</body>
</html>

hero/blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}

{% block content %}

    <div class="panel panel-info">
        <div class="panel-heading">
            <h4>{{ post.title }}</h4>
        </div>
        <div class="panel-body">
            {% if post.photo %}
            <img src="{{ post.photo.url }}" style="width: 100px;"/>
            {% endif %}

            {{ post.content|linebreaks }}
        </div>
        <div class="panel-footer">
            <a href="{% url "blog:post_list" %}" class="btn btn-primary">목록</a>
            <a href="{% url "blog:post_edit" post.id %}" class="btn btn-primary">수정</a>
        </div>
    </div>

{% endblock %}

hero/blog/templates/blog/post_form.html
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<div class="container">

    <div class="row">

        <div class="col-sm-8 col-sm-offset-2">

<form action="" method="post">
    <!-- action = "" 일 때, 현재 페이지를 가리킴 -->
    {% csrf_token %}
    <table>
        {% bootstrap_form form %}

    </table>

    <input type="submit" value="저장하기"/>
</form>
        </div>
    </div>
</div>

hero/blog/templates/blog/post_list.html
{% extends "blog/layout.html" %}

{% block content %}
    <div class="container">
        <div class="row">
        <Form action="" method="get">
            <h4>검색&nbsp;
                <select name="type">
                    <option value="title">제목</option>
                    <option value="subject">내용</option>
                </select>
            <input type="text" name="query">
            <input type="submit" value="검색" class="btn btn-info">
            </h4>
        </Form>
        </div>
        <hr>

            <a href="{% url "blog:post_new" %}" class="btn btn-warning">글쓰기</a>

            <table class="table-bordered">
                <tr>
                    <th>글 번호</th>
                    <th>글 제목</th>
                    <th>작성자</th>
                    <th>날짜</th>
                </tr>
                {% for post in post_list %}

                <tr>
                    <!-- pk는 primary key. 여기서는 인덱스 -->
                    <td>{{post.pk}}</td>
                    <td><a href="{% url "blog:post_detail" post.pk %}">
                        {{post.title}}
                    </a>
                    </td>
                    <td>{{post.author}}</td>
                    <td>{{post.created_at}}</td>
                </tr>


                {% empty %}
                <tr>
                    <td>검색 결과가 없습니다.</td>
                </tr>

                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

hero/blog/templates/blog/signup_form.html
{% extends "accounts/layout.html" %}
{% load bootstrap3 %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary btn-block" />
</form>
 {% endblock %}
 

hero/hero/templates/layout.html
{% load bootstrap3 static %}
<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>블로그</title>
{# bootstrap_css #}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/cyborg/bootstrap.min.css" />

    <script src="//code.jquery.com/jquery-2.2.4.min.js"></script>

    {% bootstrap_javascript %}


    {% block extra_head %}{% endblock %}
</head>
<body>

    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          {% block brand %}
            <a class="navbar-brand" href="#">BLOG</a>
          {% endblock %}
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            {% block extra_navbar %}{% endblock %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
             {% if not user.is_authenticated %}
                   <li><a href="{% url "login" %}">로그인</a></li>
                 <li><a href="{% url "signup" %}">회원가입</a></li>
              {% else %}
                   <li><a href="{% url "profile" %}">프로필</a></li>
                   <li><a href="{% url "logout" %}">로그아웃</a></li>
              {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1>My blog</h1>
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>

</body>
</html>

hero/shop/templates/shop/item_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

hero/shop/templates/shop/item_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>